In [1]:

import sys
import argparse
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

sys.path.append("../..")

from dataset import GeoTextDataset
from models.location_encoder import LocationEncoder
from models.text_encoder import TextEncoder

GIT10M_DIR = Path.home() / "data" / "expanded-git-10M"
SPLITS = ["train", "val", "test"]
DEVICE = "cuda"

In [ ]:
dataset = GeoTextDataset(root=GIT10M_DIR, split="test")

Saved train split: /home/libe2152/data/expanded-git-10M/train.parquet (28620134 rows)


KeyboardInterrupt: 

In [ ]:
import random

In [ ]:
indices = random.sample(range(len(dataset)), 100)

for i in indices:
    sample = dataset[i]
    print(f"\n--- Sample {i} ---")
    print(sample)


--- Sample 3618531 ---
(tensor([39.2088, -9.1077]), 'a satellite image of an agricultural field with evenly spaced rows of crops')

--- Sample 1049085 ---
(tensor([ 40.4887, 116.2546]), 'a satellite image of a dense forested area with varying shades of green and dark patches indicating tree coverage')

--- Sample 1488822 ---
(tensor([55.9430, 37.4785]), 'a satellite image of a dense forested area adjacent to a body of water, likely a river or lake')

--- Sample 2681257 ---
(tensor([ 31.6253, 121.4539]), 'a satellite image of a semi-urban area with a mix of residential buildings and green agricultural fields')

--- Sample 463656 ---
(tensor([ 38.7605, -90.1318]), 'a satellite image of a green area with dense vegetation')

--- Sample 1924248 ---
(tensor([ 71.4320, 100.7721]), 'a satellite image of a densely vegetated area with a mix of dark green and brown hues')

--- Sample 1755873 ---
(tensor([48.5548,  2.1945]), 'a satellite image of a densely forested area with a mix of tree types')

In [ ]:
import random

N = len(dataset)
subset_size = 10000  # adjust (e.g., 10k–100k depending on speed)

indices = random.sample(range(N), subset_size)

paris_lat, paris_lon = 48.8566, 2.3522

import math
def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
    return 2 * R * math.atan2(math.sqrt(a), math.sqrt(1 - a))

best = None
best_dist = float("inf")

for i in indices:
    latlon, text = dataset[i]
    lat, lon = latlon.tolist()

    dist = haversine(lat, lon, paris_lat, paris_lon)

    if dist < best_dist:
        best_dist = dist
        best = (i, latlon, text)

print(f"Closest (in subsample): {best_dist:.2f} km")
print(best)

Closest (in subsample): 1.03 km
(460168, tensor([48.8575,  2.3662]), 'a satellite image of an urban area with a mix of residential and commercial buildings')
