In [ ]:

import sys
import argparse
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

sys.path.append("../..")

from dataset import GeoTextDataset
from models.location_encoder import LocationEncoder
from models.text_encoder import TextEncoder

GIT10M_DIR = Path("../../../../data/expanded-git-10M")
SPLITS = ["train", "val", "test"]
DEVICE = "cuda"

In [2]:
dataset = GeoTextDataset(root=GIT10M_DIR, split="train")

In [3]:
import random

In [4]:
indices = random.sample(range(len(dataset)), 100)

for i in indices:
    sample = dataset[i]
    print(f"\n--- Sample {i} ---")
    print(sample)


--- Sample 1637730 ---
(tensor([ 32.4078, -93.8960]), 'large house')

--- Sample 335529 ---
(tensor([ 31.5458, 120.4761]), 'some brown patches')

--- Sample 637203 ---
(tensor([52.5730, 13.4143]), 'residential and commercial buildings')

--- Sample 2799454 ---
(tensor([40.3277, 77.4811]), 'bodies of water')

--- Sample 2792862 ---
(tensor([19.0881, 72.8970]), 'primarily residential structures')

--- Sample 2541230 ---
(tensor([ 40.6348, 117.0813]), 'few narrow dirt roads')

--- Sample 2601704 ---
(tensor([ 39.2759, -94.6733]), 'central area with a swimming pool')

--- Sample 2185029 ---
(tensor([ 40.8200, -74.1660]), 'residential neighborhood with a grid-like street pattern')

--- Sample 106074 ---
(tensor([38.1173, 87.2974]), 'valleys')

--- Sample 2129955 ---
(tensor([48.9847,  2.5571]), 'sac')

--- Sample 339053 ---
(tensor([ 38.8097, -90.6564]), 'Trees')

--- Sample 3103113 ---
(tensor([ 25.9975, -97.5037]), 'Each house')

--- Sample 2336223 ---
(tensor([ 38.1086, -99.0527]), 'oth

In [6]:
import random

N = len(dataset)
subset_size = 10000  # adjust (e.g., 10k–100k depending on speed)

indices = random.sample(range(N), subset_size)

my_lat, my_lon = 27.9881, 86.9250

import math
def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
    return 2 * R * math.atan2(math.sqrt(a), math.sqrt(1 - a))

best = None
best_dist = float("inf")

for i in indices:
    latlon, text = dataset[i]
    lat, lon = latlon.tolist()

    dist = haversine(lat, lon, my_lat, my_lon)

    if dist < best_dist:
        best_dist = dist
        best = (i, latlon, text)

print(f"Closest (in subsample): {best_dist:.2f} km")
print(best)

Closest (in subsample): 117.52 km
(648207, tensor([28.3044, 85.7812]), 'ice')
